### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tomkirkhawkeye** [tomasbkk/action-ftp-upload#3]
I'd like to use this action in my workflow but I need the secure flag which isn't a valid input in the 1.0 release (but was fixed in #1 . Would you be able to do a new release with this included?

**Comment by tomasbkk** [comment]
Done, let me know if I done it right

**Comment by tomkirkhawkeye** [comment]
Hello,

That did expose the setting, but it looks like it is parsing it as a string and therefore not treating it as secure. I'd like to make a PR to fix that. Additionally, for our use case our FTP uses a self-signed cert which basic-ftp fails on. Would you have any objection to me adding support for self signing? For reference, this seems to work by adding the following to client.access
```
      secureOptions: { rejectUnauthorized: false },
```

**Comment by tomasbkk** [comment]
I've made another release, hopefully this one works.

**Comment by tomkirkhawkeye** [comment]
Yes works perfectly, thank you!
